---
title: "Assignment 1"
author: "Doug Goon"
date: "April 25, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x <- scan("read_this_1.txt")
```

```{r}
length(x)
```

```{r}
sum(x)
```

```{r}
mean(x)
```

```{r}
csv <- read.csv("read_this_1.csv")
```

### Basic R Exercise 1

1. 

```{r}
a <- c(1:20)
b <- c(20:1)
c <- c(1:19,20,19:1)
tmp <-c(4,6,3)
e <- rep(tmp, times = 10)
f <- rep(tmp, times = 10, length = 31)
g <- rep(tmp, times=c(10,20,30))
```

2. 

```{r}
x <- seq(3, 6, by=.1) 
Q2 <- (exp(1)^x)*cos(x)
```

3. 
(a) 
```{r}
Q3A_num <- c(1:12)
Q3A <-((0.1^(3*Q3A_num))*(0.2^(-2+3*Q3A_num)))
```

(b) 
```{r}
Q3B_num <- c(1:25)
Q3B <- ((2^Q3B_num)/Q3B_num)
```

4. 
(a)
```{r}
Q4A_num <- c(10:100)
sum((Q4A_num^3) + 4 * (Q4A_num^2))
```

(b)
```{r}
Q4B_num <- c(1:25)
sum(( (2^Q4B_num) / Q4B_num) + ( (3^Q4B_num) / (Q4B_num^2)))
```

5
(a)
```{r}
Q5A <- paste(c("label "), 1:30)
```

(b)
```{r}
Q5B <- paste(c("fn"), 1:30, sep = "")
```

6.
```{r}
set.seed(50) 
xVec <-sample(0:999, 250, replace = T)
yVec <-sample(0:999, 250, replace = T)
```

(a)
```{r}
Q6A <- yVec[-1] - xVec[-length(xVec)]
```

(b)
```{r}
Q6B <- (sin(yVec[-length(yVec)]))/cos(xVec[-1])
```

(c)
```{r}
Q6C <- xVec[-c(249,250)] + 2*xVec[-c(1,250)]-xVec[-c(1,2)]
```

(d)
```{r}
sum( (exp(1)^(-xVec[-1])) / (xVec[-length(xVec)] + 10))
```

7.
(a)
```{r}
yVec[yVec>600]
```

(b)
```{r}
which(yVec > 600)
```

(c)
```{r}
xVec[which(yVec>600)]
```

(d)
```{r}
Q7D <- sqrt(abs(xVec - mean(xVec)))
```

(e)
```{r}
sum(yVec>(max(yVec)-200))
```

(f)
```{r}
sum(xVec %% 2 == 0)
```

(g)
```{r}
xVec[order(yVec)]
```

(h)
```{r}
yVec[c(T,F,F)]
```

8.
```{r}
1+sum(cumprod(seq(2,38, by = 2)/seq(3,39, by = 2)))
```




